substitutions:
  name: ventola-raspberry # Do not use underscores, which are not fully compatible with mDNS
  friendly_name: Ventola Raspberry
  version: "1.0.0"
  speed_low: "35"
  speed_medium: "50"
  speed_high: "75"
  speed_full: "100"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "soloam.fan_controller"
    version: "${version}"
  on_boot:
    then:
      - delay: 10s
      - fan.turn_on:
          id: fan_speed
          speed: "${speed_low}"
      - delay: 5s
      - fan.turn_on:
          id: fan_speed
          speed: "${speed_medium}"

esp8266:
  board: d1_mini

# Enable logging
logger:
#  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: "!ChangeMe!"

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} ESP"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  topic_prefix: "esphome/${name}"

output:
  - platform: esp8266_pwm
    pin: D4
    frequency: 15000 Hz
    id: pwm_output

fan:
  - platform: speed
    id: fan_speed
    output: pwm_output
    speed_count: 100
    name: "${friendly_name} Fan"
    command_topic: "esphome/${name}/fan/command"
    state_topic: "esphome/${name}/fan/state"

number:
  - platform: template
    icon: "mdi:fan"
    id: speed_input
    name: "${friendly_name} Fan Speed"
    lambda: |-
      return id(fan_speed).speed;
    step: 1
    min_value: 1
    max_value: 100
    unit_of_measurement: "%"
    update_interval: 1s
    set_action:
      then:
        - fan.turn_on:
            id: fan_speed
            speed: !lambda "return x;"
        - component.update: sensor_fanmode
        - component.update: sensor_fanspeed

text_sensor:
  - platform: template
    icon: "mdi:fan"
    name: "${friendly_name} Fan Mode"
    id: sensor_fanmode
    update_interval: 1s
    lambda: |-
      if (id(fan_speed).speed <= ${speed_low}) {
        return {"Low"};
      } else if (id(fan_speed).speed <= ${speed_medium}) {
        return {"Medium"};
      } else if (id(fan_speed).speed <= ${speed_high}) {
        return {"High"};
      } else if (id(fan_speed).speed <= ${speed_full}) {
        return {"Full"};
      } else {
        return {"Custom"};
      }

button:
  - platform: template
    icon: "mdi:fan-speed-1"
    name: "${friendly_name} Set Low Speed"
    id: fanlow
    on_press:
      - fan.turn_on:
          id: fan_speed
          speed: "${speed_low}"
  - platform: template
    icon: "mdi:fan-speed-2"
    name: "${friendly_name} Set Medium Speed"
    on_press:
      - fan.turn_on:
          id: fan_speed
          speed: "${speed_medium}"
  - platform: template
    icon: "mdi:fan-speed-3"
    name: "${friendly_name} Set High Speed"
    on_press:
      - fan.turn_on:
          id: fan_speed
          speed: "${speed_high}"
  - platform: template
    icon: "mdi:fan-alert"
    name: "${friendly_name} Set Full Speed"
    on_press:
      - fan.turn_on:
          id: fan_speed
          speed: "${speed_full}"
  - platform: restart
    name: "${friendly_name} Restart"

sensor:
  - platform: template
    id: sensor_fanspeed
    icon: "mdi:fan"
    name: "${friendly_name} Fan Speed"
    lambda: |-
      return id(fan_speed).speed;
    update_interval: 1s
    accuracy_decimals: 0
    unit_of_measurement: "%"
  - platform: dht
    pin: D2
    temperature:
      name: "${friendly_name} Temperature"
    humidity:
      name: "${friendly_name} Humidity"
    update_interval: 30s
    model: DHT22
  - platform: pulse_counter
    icon: "mdi:fan"
    pin:
      number: D3
      # Abilitiamo la resistenza di pullup interna per stabilizzare il segnale
      mode: INPUT_PULLUP
    name: "${friendly_name} RPM"
    unit_of_measurement: rpm
    accuracy_decimals: 0
    update_interval: 3s  # <--- Aumentato per stabilizzare il calcolo matematico
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    filters:
      # 1. Riconosce come impulsi validi solo quelli distanti almeno 15 millisecondi
      #    (adatto a ventole fino a oltre 4000 RPM)
      - debounce: 15ms  
      # 2. Moltiplica per 0.5 (perché le ventole PC inviano 2 impulsi a rotazione)
      - multiply: 0.5
